variable "region_name" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "project_name" {}
variable "client_name" {}
variable "application_name" {}
variable "environment_name" {}
variable "os_name" {}
variable "os_type" {}
variable "default_tags" {}
