region = "us-east-1"
vpc_name = "AHS_Prod_App_VPC"
subnet_name = "AHS_Prod_App_AZ-B"
subnet_cidr = "10.126.192.32/27"
subnet_az = "$SUBNET_AZ"

tag_name = "AHS_Prod_App_AZ-B"
project_name = "Symphony"
organization_name = "Advantasure Inc."
client_name = "AHS"
