variable "region_name" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "key_name" {}
variable "instance_type" {}
variable "min_instance_size" {}
variable "desired_capacity" {}
variable "max_instance_size" {}
variable "user_data_file" {}
variable "default_tags" {}
variable "join_to_ad" {}
