variable "region_name" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "cluster_id" {}
variable "engine_name" {}
variable "engine_version" {}
variable "node_type" {}
variable "num_cache_nodes" {}
#variable "num_node_groups" {}
variable "parameter_group_name" {}
variable "port" {}
variable "project_name" {}
variable "client_name" {}
variable "environment_name" {}
variable "zone_name" {}
